### ISSUE TITLE
error，the repos not find

### ISSUE THREAD

**Issue by jim-sang** [opusb/tpclash2#1]
jq: error (at <stdin>:4): Cannot iterate over null (null)
task: Failed to run task "default": task: Command "curl -sSL  \
  https://api.github.com/repos/Dreamacro/clash/releases/tags/premium | \
  jq -r '.assets[].browser_download_url | select (. | test("clash-linux-386-\\d{4}.*gz"))'
" failed: exit status 5

大哥，这个问题怎么解决？

**Comment by opusb** [comment]
sudo apt install jq

**Comment by opusb** [comment]
编译过的 https://github.com/opusb/tpclash/releases/tag/0.1.17

**Comment by jim-sang** [comment]
> https://api.github.com/repos/Dreamacro/clash/releases/tags/premium 替换 https://api.github.com/repos/opusb/clash/releases/tags/premium sudo apt install jq 或者 sudo apt-get install -y jq

谢谢，回头试试
